stages:
- name: test
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: ./FlonkaTestApp/gradlew build
  - runScriptConfig:
      image: java:8
      shellScript: ./FlonkaTestApp/gradlew unpack
  - publishImageConfig:
      dockerfilePath: ./FlonkaTestApp/Dockerfile
      buildContext: .
      tag: stohanean/flonka-app:test
      registry: 127.0.0.1:34509
- name: prod
  steps:
  - publishImageConfig:
      dockerfilePath: ./FlonkaTestApp/Dockerfile
      buildContext: .
      tag: stohanean/flonka-app:prod
      registry: 127.0.0.1:34509
timeout: 60
branch: {}
