stages:
- name: Build
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: ./gradlew clean build unpack
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: stohanean/flonka-app
      registry: 127.0.0.1:34509
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
