stages:
- name: test
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: stohanean/flonka-app:test
      registry: 127.0.0.1:34509
- name: prod
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: stohanean/flonka-app:prod
      registry: 127.0.0.1:34509
timeout: 60
branch: {}
